// 側欄＝依 docs/ 目錄結構自動生成（章＝資料夾＋_category_.json、節＝md 檔）。
import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
const sidebars: SidebarsConfig = {
  manual: [{ type: "autogenerated", dirName: "." }],
};
export default sidebars;
