// 計算模組（README §5）— 純函數彙整出口
export * from "./brackets";
export * from "./seniority";
export * from "./wage";
export * from "./dependents";
export * from "./insurance";
export * from "./supplementary";
export * from "./tax";
export * from "./payroll";
